// <auto-generated />
using System;
using MecanoERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MecanoERP.Infrastructure.Migrations
{
    [DbContext(typeof(MecanoDbContext))]
    partial class MecanoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MecanoERP.Core.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ConsentementEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("ConsentementSMS")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NotesInternes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Solde")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.CommandeAchat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateReception")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.ToTable("CommandesAchat");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Comptabilite.CompteGL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompteParentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstSysteme")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Solde")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SousType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeCompte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompteParentId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("ComptesGL");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Comptabilite.ConfigFournisseurCompta", b =>
                {
                    b.Property<int>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompteGLCTI_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("CompteGLChargeId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstInscritTPS")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstInscritTVQ")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LimiteCredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroTPS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroTVH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroTVQ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Termes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeFournisseur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FournisseurId");

                    b.HasIndex("CompteGLChargeId");

                    b.ToTable("ConfigsFournisseurs");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Comptabilite.ConfigurationFiscale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompteGLTPS_PercueId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompteGLTPS_RecuperableId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompteGLTVH_PercueId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompteGLTVQ_PercueId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompteGLTVQ_RecuperableId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateMiseAJour")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NomProvince")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroInscriptionTPS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroInscriptionTVH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroInscriptionTVQ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TauxTPS")
                        .HasPrecision(6, 5)
                        .HasColumnType("numeric(6,5)");

                    b.Property<decimal?>("TauxTVH")
                        .HasPrecision(6, 5)
                        .HasColumnType("numeric(6,5)");

                    b.Property<decimal>("TauxTVQ")
                        .HasPrecision(6, 5)
                        .HasColumnType("numeric(6,5)");

                    b.HasKey("Id");

                    b.ToTable("ConfigurationsFiscales");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Comptabilite.JournalComptable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommandeAchatId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstAnnule")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstBrouillon")
                        .HasColumnType("boolean");

                    b.Property<int?>("FactureId")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TypeJournal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Journaux");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Comptabilite.LigneJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompteGLId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Credit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Debit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JournalComptableId")
                        .HasColumnType("integer");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompteGLId");

                    b.HasIndex("JournalComptableId");

                    b.ToTable("LignesJournal");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.EcritureComptable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommandeAchatId")
                        .HasColumnType("integer");

                    b.Property<string>("Compte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CompteGLId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Credit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Debit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FactureId")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompteGLId");

                    b.ToTable("EcrituresComptables");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TauxCommission")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TauxHoraire")
                        .HasColumnType("numeric");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int?>("ConfigurationFiscaleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateEcheance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("JournalComptableId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontantHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MontantPaye")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NumeroTPS_Garage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroTVH_Garage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroTVQ_Garage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrdreTravailId")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<decimal>("TauxTPS")
                        .HasPrecision(6, 5)
                        .HasColumnType("numeric(6,5)");

                    b.Property<decimal?>("TauxTVH")
                        .HasPrecision(6, 5)
                        .HasColumnType("numeric(6,5)");

                    b.Property<decimal>("TauxTVQ")
                        .HasPrecision(6, 5)
                        .HasColumnType("numeric(6,5)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ConfigurationFiscaleId");

                    b.HasIndex("JournalComptableId");

                    b.HasIndex("OrdreTravailId");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroCompte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Garantie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FactureId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.ToTable("Garanties");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Identite.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Module", "Action")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Identite.RoleApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstSysteme")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Identite.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Identite.UtilisateurApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DernierConnexion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Sel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NomUtilisateur")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.LigneCommandeAchat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeAchatId")
                        .HasColumnType("integer");

                    b.Property<int>("PieceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteRecue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommandeAchatId");

                    b.HasIndex("PieceId");

                    b.ToTable("LignesCommandeAchat");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.LigneOT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrdreTravailId")
                        .HasColumnType("integer");

                    b.Property<int?>("PieceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Rabais")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrdreTravailId");

                    b.HasIndex("PieceId");

                    b.ToTable("LignesOT");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Lu")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrdreTravailId")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.OrdreTravail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEntree")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateSortie")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diagnostic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("integer");

                    b.Property<int>("KilometrageEntree")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("SignatureClient")
                        .HasColumnType("boolean");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<decimal>("TempsEstime")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TempsReel")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("TravauxDemandes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.HasIndex("VehiculeId");

                    b.ToTable("OrdresTravail");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FactureId")
                        .HasColumnType("integer");

                    b.Property<int>("ModePaiement")
                        .HasColumnType("integer");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Piece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeBarres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emplacement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixAchat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PrixVente")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StockActuel")
                        .HasColumnType("integer");

                    b.Property<int>("StockMinimum")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.ToTable("Pieces");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.RendezVous", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DureeMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RappelEnvoye")
                        .HasColumnType("boolean");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("TypeService")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VehiculeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeId");

                    b.HasIndex("VehiculeId");

                    b.ToTable("RendezVous");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Vehicule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Annee")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kilometrage")
                        .HasColumnType("integer");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeMoteur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Vehicules");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.CommandeAchat", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.Fournisseur", "Fournisseur")
                        .WithMany("CommandesAchat")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Comptabilite.CompteGL", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.Comptabilite.CompteGL", "CompteParent")
                        .WithMany("SousComptes")
                        .HasForeignKey("CompteParentId");

                    b.Navigation("CompteParent");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Comptabilite.ConfigFournisseurCompta", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.Comptabilite.CompteGL", "CompteGLCharge")
                        .WithMany()
                        .HasForeignKey("CompteGLChargeId");

                    b.HasOne("MecanoERP.Core.Entities.Fournisseur", "Fournisseur")
                        .WithOne()
                        .HasForeignKey("MecanoERP.Core.Entities.Comptabilite.ConfigFournisseurCompta", "FournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteGLCharge");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Comptabilite.LigneJournal", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.Comptabilite.CompteGL", "CompteGL")
                        .WithMany("LignesJournal")
                        .HasForeignKey("CompteGLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecanoERP.Core.Entities.Comptabilite.JournalComptable", "Journal")
                        .WithMany("Lignes")
                        .HasForeignKey("JournalComptableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteGL");

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.EcritureComptable", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.Comptabilite.CompteGL", "CompteGL")
                        .WithMany()
                        .HasForeignKey("CompteGLId");

                    b.Navigation("CompteGL");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Facture", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.Client", "Client")
                        .WithMany("Factures")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecanoERP.Core.Entities.Comptabilite.ConfigurationFiscale", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationFiscaleId");

                    b.HasOne("MecanoERP.Core.Entities.Comptabilite.JournalComptable", "JournalComptable")
                        .WithMany()
                        .HasForeignKey("JournalComptableId");

                    b.HasOne("MecanoERP.Core.Entities.OrdreTravail", "OrdreTravail")
                        .WithMany("Factures")
                        .HasForeignKey("OrdreTravailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("JournalComptable");

                    b.Navigation("OrdreTravail");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Garantie", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.Facture", "Facture")
                        .WithMany("Garanties")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Identite.RolePermission", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.Identite.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecanoERP.Core.Entities.Identite.RoleApp", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Identite.UtilisateurApp", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.Identite.RoleApp", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.LigneCommandeAchat", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.CommandeAchat", "CommandeAchat")
                        .WithMany("Lignes")
                        .HasForeignKey("CommandeAchatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecanoERP.Core.Entities.Piece", "Piece")
                        .WithMany("LignesCommande")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommandeAchat");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.LigneOT", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.OrdreTravail", "OrdreTravail")
                        .WithMany("Lignes")
                        .HasForeignKey("OrdreTravailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecanoERP.Core.Entities.Piece", "Piece")
                        .WithMany("LignesOT")
                        .HasForeignKey("PieceId");

                    b.Navigation("OrdreTravail");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.OrdreTravail", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.Employe", "Employe")
                        .WithMany("OrdresTravail")
                        .HasForeignKey("EmployeId");

                    b.HasOne("MecanoERP.Core.Entities.Vehicule", "Vehicule")
                        .WithMany("OrdresTravail")
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Paiement", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.Facture", "Facture")
                        .WithMany("Paiements")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Piece", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.Fournisseur", "Fournisseur")
                        .WithMany("Pieces")
                        .HasForeignKey("FournisseurId");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.RendezVous", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.Client", "Client")
                        .WithMany("RendezVous")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecanoERP.Core.Entities.Employe", "Employe")
                        .WithMany()
                        .HasForeignKey("EmployeId");

                    b.HasOne("MecanoERP.Core.Entities.Vehicule", "Vehicule")
                        .WithMany("RendezVous")
                        .HasForeignKey("VehiculeId");

                    b.Navigation("Client");

                    b.Navigation("Employe");

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Vehicule", b =>
                {
                    b.HasOne("MecanoERP.Core.Entities.Client", "Client")
                        .WithMany("Vehicules")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Client", b =>
                {
                    b.Navigation("Factures");

                    b.Navigation("RendezVous");

                    b.Navigation("Vehicules");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.CommandeAchat", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Comptabilite.CompteGL", b =>
                {
                    b.Navigation("LignesJournal");

                    b.Navigation("SousComptes");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Comptabilite.JournalComptable", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Employe", b =>
                {
                    b.Navigation("OrdresTravail");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Facture", b =>
                {
                    b.Navigation("Garanties");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Fournisseur", b =>
                {
                    b.Navigation("CommandesAchat");

                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Identite.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Identite.RoleApp", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.OrdreTravail", b =>
                {
                    b.Navigation("Factures");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Piece", b =>
                {
                    b.Navigation("LignesCommande");

                    b.Navigation("LignesOT");
                });

            modelBuilder.Entity("MecanoERP.Core.Entities.Vehicule", b =>
                {
                    b.Navigation("OrdresTravail");

                    b.Navigation("RendezVous");
                });
#pragma warning restore 612, 618
        }
    }
}
